// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestorantApp;

// RemovePaymentMethodFromOrder.Designer.cs
#nullable disable
namespace RestorantApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603174359_RemovePaymentMethodFromOrder")]
    partial class RemovePaymentMethodFromOrder
    {
        // Vetëm metadata e migrimit, pa metodat Up() dhe Down()
    }
}
